<?php

namespace Container8CCd9zC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Application\Comment\CommentService' shared autowired service.
     *
     * @return \App\Application\Comment\CommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Comment/CommentService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Comment/CommentRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/Repository/CommentRepository.php';

        return $container->privates['App\\Application\\Comment\\CommentService'] = new \App\Application\Comment\CommentService(new \App\Infrastructure\Persistence\Doctrine\Repository\CommentRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));
    }
}
