<?php

namespace Container8CCd9zC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Application\Profile\ProfileService' shared autowired service.
     *
     * @return \App\Application\Profile\ProfileService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Profile/ProfileService.php';

        return $container->privates['App\\Application\\Profile\\ProfileService'] = new \App\Application\Profile\ProfileService(($container->privates['App\\Domain\\User\\UserRepositoryInterface'] ?? $container->load('getUserRepositoryInterfaceService')));
    }
}
