<?php

namespace Container8CCd9zC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRepositoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Domain\Tag\TagRepositoryInterface' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\Doctrine\Repository\TagRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Tag/TagRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/Repository/TagRepository.php';

        return $container->privates['App\\Domain\\Tag\\TagRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\Repository\TagRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
