<?php

namespace Container8CCd9zC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRepositoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Domain\User\UserRepositoryInterface' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\Doctrine\Repository\UserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/User/UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/Repository/UserRepository.php';

        return $container->privates['App\\Domain\\User\\UserRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\Repository\UserRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
