<?php

namespace Container8CCd9zC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Ui\Http\Controller\UserController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Ui/Http/Controller/UserController.php';
        include_once \dirname(__DIR__, 4).'/src/Ui/Http/Request/JsonRequestBodyParser.php';
        include_once \dirname(__DIR__, 4).'/src/Ui/Http/Response/RealWorldResponseFactory.php';

        return $container->services['App\\Ui\\Http\\Controller\\UserController'] = new \App\Ui\Http\Controller\UserController(($container->privates['App\\Application\\User\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['App\\Ui\\Http\\Request\\JsonRequestBodyParser'] ??= new \App\Ui\Http\Request\JsonRequestBodyParser()), ($container->privates['App\\Ui\\Http\\Response\\RealWorldResponseFactory'] ??= new \App\Ui\Http\Response\RealWorldResponseFactory()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
