doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true
        driver: 'pdo_sqlite'
        charset: 'utf8mb4'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        report_fields_where_declared: true
        enable_lazy_ghost_objects: true
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            Domain:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: Domain
