framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    serializer: { enable_attributes: true }
    validation:
        enabled: true
        email_validation_mode: html5
    cache:
        app: cache.adapter.filesystem
