security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/articles/feed$, roles: ROLE_USER }
        - { path: ^/api/articles/[^/]+/favorite$, roles: ROLE_USER }
        - { path: ^/api/articles/[^/]+/comments$, roles: ROLE_USER, methods: [POST] }
        - { path: ^/api/articles/[^/]+/comments/\d+$, roles: ROLE_USER, methods: [DELETE] }
        - { path: ^/api/articles$, roles: ROLE_USER, methods: [POST] }
        - { path: ^/api/articles/[^/]+$, roles: ROLE_USER, methods: [PUT,DELETE] }
        - { path: ^/api/profiles/[^/]+/follow$, roles: ROLE_USER }
        - { path: ^/api/user$, roles: ROLE_USER }
