<?php

namespace ContainerBEbho5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Ui\Http\Controller\AuthController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\AuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Ui\\Http\\Controller\\AuthController'] = new \App\Ui\Http\Controller\AuthController(($container->privates['App\\Application\\User\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['App\\Ui\\Http\\Request\\JsonRequestBodyParser'] ??= new \App\Ui\Http\Request\JsonRequestBodyParser()), ($container->privates['App\\Ui\\Http\\Response\\RealWorldResponseFactory'] ??= new \App\Ui\Http\Response\RealWorldResponseFactory()));
    }
}
