<?php

namespace ContainerBEbho5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Application\Article\ArticleService' shared autowired service.
     *
     * @return \App\Application\Article\ArticleService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Application\\Article\\ArticleService'] = new \App\Application\Article\ArticleService(new \App\Infrastructure\Persistence\Doctrine\Repository\ArticleRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))), ($container->privates['App\\Domain\\Tag\\TagRepositoryInterface'] ?? $container->load('getTagRepositoryInterfaceService')), ($container->privates['App\\Domain\\User\\UserRepositoryInterface'] ?? $container->load('getUserRepositoryInterfaceService')), new \Cocur\Slugify\Slugify());
    }
}
