<?php

namespace ContainerBEbho5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Application\Comment\CommentService' shared autowired service.
     *
     * @return \App\Application\Comment\CommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Application\\Comment\\CommentService'] = new \App\Application\Comment\CommentService(new \App\Infrastructure\Persistence\Doctrine\Repository\CommentRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));
    }
}
