<?php

namespace ContainerBEbho5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedDatabaseCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Ui\Console\SeedDatabaseCommand' shared autowired service.
     *
     * @return \App\Ui\Console\SeedDatabaseCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Ui\\Console\\SeedDatabaseCommand'] = $instance = new \App\Ui\Console\SeedDatabaseCommand(new \App\Infrastructure\Persistence\DataFixtures\DatabaseSeeder(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Application\\User\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['App\\Application\\Profile\\ProfileService'] ?? $container->load('getProfileServiceService')), ($container->privates['App\\Application\\Article\\ArticleService'] ?? $container->load('getArticleServiceService')), ($container->privates['App\\Application\\Comment\\CommentService'] ?? $container->load('getCommentServiceService'))));

        $instance->setName('app:seed');
        $instance->setAliases(['app:seed']);
        $instance->setDescription('Seed the database with demo data for the RealWorld API');

        return $instance;
    }
}
