<?php

namespace ContainerBEbho5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Application\User\UserService' shared autowired service.
     *
     * @return \App\Application\User\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Application\\User\\UserService'] = new \App\Application\User\UserService(($container->privates['App\\Domain\\User\\UserRepositoryInterface'] ?? $container->load('getUserRepositoryInterfaceService')), new \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService'))), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')));
    }
}
