<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleFavoriteControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Ui\Http\Controller\ArticleFavoriteController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\ArticleFavoriteController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Ui\\Http\\Controller\\ArticleFavoriteController'] = new \App\Ui\Http\Controller\ArticleFavoriteController(($container->privates['App\\Application\\Article\\ArticleService'] ?? $container->load('getArticleServiceService')), ($container->privates['App\\Ui\\Http\\Response\\RealWorldResponseFactory'] ??= new \App\Ui\Http\Response\RealWorldResponseFactory()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
