<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Application\Comment\CommentService' shared autowired service.
     *
     * @return \App\Application\Comment\CommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Application\\Comment\\CommentService'] = new \App\Application\Comment\CommentService(($container->privates['App\\Domain\\Comment\\CommentRepositoryInterface'] ?? $container->load('getCommentRepositoryInterfaceService')));
    }
}
