<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentRepositoryInterfaceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Domain\Comment\CommentRepositoryInterface' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\Doctrine\Repository\CommentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Domain\\Comment\\CommentRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\Repository\CommentRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
