<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCocurSlugifyService extends App_KernelTestContainer
{
    /*
     * Gets the private 'cocur_slugify' shared autowired service.
     *
     * @return \Cocur\Slugify\Slugify
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['cocur_slugify'] = new \Cocur\Slugify\Slugify();
    }
}
