<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonExceptionSubscriberService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Ui\Http\EventSubscriber\JsonExceptionSubscriber' shared autowired service.
     *
     * @return \App\Ui\Http\EventSubscriber\JsonExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Ui\\Http\\EventSubscriber\\JsonExceptionSubscriber'] = new \App\Ui\Http\EventSubscriber\JsonExceptionSubscriber(($container->privates['logger'] ?? self::getLoggerService($container)), false);
    }
}
