<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Ui\Http\Controller\ProfileController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\ProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Ui\\Http\\Controller\\ProfileController'] = new \App\Ui\Http\Controller\ProfileController(($container->privates['App\\Application\\Profile\\ProfileService'] ?? $container->load('getProfileServiceService')), ($container->privates['App\\Ui\\Http\\Response\\RealWorldResponseFactory'] ??= new \App\Ui\Http\Response\RealWorldResponseFactory()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
