<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealWorldResponseFactoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Ui\Http\Response\RealWorldResponseFactory' shared autowired service.
     *
     * @return \App\Ui\Http\Response\RealWorldResponseFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Ui\\Http\\Response\\RealWorldResponseFactory'] = new \App\Ui\Http\Response\RealWorldResponseFactory();
    }
}
