<?php

namespace ContainerBur3GMZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Ui\Http\Controller\TagController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Ui\\Http\\Controller\\TagController'] = new \App\Ui\Http\Controller\TagController(($container->privates['App\\Application\\Tag\\TagService'] ?? $container->load('getTagServiceService')));
    }
}
