<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleRepositoryInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Domain\Article\ArticleRepositoryInterface' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\Doctrine\Repository\ArticleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Article/ArticleRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/Repository/ArticleRepository.php';

        return $container->privates['App\\Domain\\Article\\ArticleRepositoryInterface'] = new \App\Infrastructure\Persistence\Doctrine\Repository\ArticleRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
