<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Article\ArticleService' shared autowired service.
     *
     * @return \App\Application\Article\ArticleService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Article/ArticleService.php';
        include_once \dirname(__DIR__, 4).'/vendor/cocur/slugify/src/SlugifyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/cocur/slugify/src/Slugify.php';

        return $container->privates['App\\Application\\Article\\ArticleService'] = new \App\Application\Article\ArticleService(($container->privates['App\\Domain\\Article\\ArticleRepositoryInterface'] ?? $container->load('getArticleRepositoryInterfaceService')), ($container->privates['App\\Domain\\Tag\\TagRepositoryInterface'] ?? $container->load('getTagRepositoryInterfaceService')), ($container->privates['App\\Domain\\User\\UserRepositoryInterface'] ?? $container->load('getUserRepositoryInterfaceService')), ($container->privates['cocur_slugify'] ??= new \Cocur\Slugify\Slugify()));
    }
}
