<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Comment\CommentService' shared autowired service.
     *
     * @return \App\Application\Comment\CommentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Comment/CommentService.php';

        return $container->privates['App\\Application\\Comment\\CommentService'] = new \App\Application\Comment\CommentService(($container->privates['App\\Domain\\Comment\\CommentRepositoryInterface'] ?? $container->load('getCommentRepositoryInterfaceService')));
    }
}
