<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCocurSlugifyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'cocur_slugify' shared autowired service.
     *
     * @return \Cocur\Slugify\Slugify
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/cocur/slugify/src/SlugifyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/cocur/slugify/src/Slugify.php';

        return $container->privates['cocur_slugify'] = new \Cocur\Slugify\Slugify();
    }
}
