<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseSeederService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Persistence\DataFixtures\DatabaseSeeder' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\DataFixtures\DatabaseSeeder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/DataFixtures/DatabaseSeeder.php';

        return $container->privates['App\\Infrastructure\\Persistence\\DataFixtures\\DatabaseSeeder'] = new \App\Infrastructure\Persistence\DataFixtures\DatabaseSeeder(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Application\\User\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['App\\Application\\Profile\\ProfileService'] ?? $container->load('getProfileServiceService')), ($container->privates['App\\Application\\Article\\ArticleService'] ?? $container->load('getArticleServiceService')), ($container->privates['App\\Application\\Comment\\CommentService'] ?? $container->load('getCommentServiceService')));
    }
}
