<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedDatabaseCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Ui\Console\SeedDatabaseCommand' shared autowired service.
     *
     * @return \App\Ui\Console\SeedDatabaseCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Ui/Console/SeedDatabaseCommand.php';

        $container->privates['App\\Ui\\Console\\SeedDatabaseCommand'] = $instance = new \App\Ui\Console\SeedDatabaseCommand(($container->privates['App\\Infrastructure\\Persistence\\DataFixtures\\DatabaseSeeder'] ?? $container->load('getDatabaseSeederService')));

        $instance->setName('app:seed');
        $instance->setAliases(['app:seed']);
        $instance->setDescription('Seed the database with demo data for the RealWorld API');

        return $instance;
    }
}
