<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedDatabaseCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Ui\Console\SeedDatabaseCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Ui\\Console\\SeedDatabaseCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:seed', ['app:seed'], 'Seed the database with demo data for the RealWorld API', false, #[\Closure(name: 'App\\Ui\\Console\\SeedDatabaseCommand')] fn (): \App\Ui\Console\SeedDatabaseCommand => ($container->privates['App\\Ui\\Console\\SeedDatabaseCommand'] ?? $container->load('getSeedDatabaseCommandService')));
    }
}
