<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Ui\Http\Controller\TagController' shared autowired service.
     *
     * @return \App\Ui\Http\Controller\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Ui/Http/Controller/TagController.php';

        return $container->services['App\\Ui\\Http\\Controller\\TagController'] = new \App\Ui\Http\Controller\TagController(($container->privates['App\\Application\\Tag\\TagService'] ?? $container->load('getTagServiceService')));
    }
}
