<?php

namespace ContainerKY0BNkr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Tag\TagService' shared autowired service.
     *
     * @return \App\Application\Tag\TagService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Tag/TagService.php';

        return $container->privates['App\\Application\\Tag\\TagService'] = new \App\Application\Tag\TagService(($container->privates['App\\Domain\\Tag\\TagRepositoryInterface'] ?? $container->load('getTagRepositoryInterfaceService')));
    }
}
