<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKY0BNkr\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKY0BNkr/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKY0BNkr.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKY0BNkr\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerKY0BNkr\App_KernelTestDebugContainer([
    'container.build_hash' => 'KY0BNkr',
    'container.build_id' => 'af267eaa',
    'container.build_time' => 1760634476,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKY0BNkr');
