<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBur3GMZ\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBur3GMZ/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerBur3GMZ.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerBur3GMZ\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerBur3GMZ\App_KernelTestContainer([
    'container.build_hash' => 'Bur3GMZ',
    'container.build_id' => 'c41791fa',
    'container.build_time' => 1760634243,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBur3GMZ');
