<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEbho5f\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEbho5f/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerBEbho5f.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerBEbho5f\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerBEbho5f\App_KernelDevContainer([
    'container.build_hash' => 'BEbho5f',
    'container.build_id' => 'fa1b3104',
    'container.build_time' => 1760634516,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEbho5f');
